In [1]:
import numpy as np

In [2]:
# lets craete array

In [3]:
arr = np.arange(1,15,5)

In [4]:
arr

array([ 1,  6, 11])

In [5]:
arr_rand = np.random.randint(1,100,5)

In [6]:
arr_rand

array([60, 31, 60, 81, 87])

In [7]:
arr_rand[1]

31

In [8]:
# we can get values from array like list indexing also.

In [9]:
arr[2]

11

In [10]:
arr_10 = np.arange(1,15)

In [11]:
arr_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr_10[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# lets just say if we want to assign all values from array same value 

In [14]:
arr_10[:] =7

In [15]:
arr_10

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [16]:
# thats how we can assign same value to all array index.

In [17]:
arr_10[:5] = 21

In [18]:
arr_10

array([21, 21, 21, 21, 21,  7,  7,  7,  7,  7,  7,  7,  7,  7])

In [19]:
# we can also assign this value to specific index of array

In [20]:
# we can aslo assign some index values to new array like list

In [21]:
slice_arr = arr_10[1:6]

In [22]:
slice_arr

array([21, 21, 21, 21,  7])

In [23]:
# now if we cahnge this slice_arr value it will change arr_10 values as well

In [24]:
# see 
slice_arr[:] = 121

In [25]:
slice_arr

array([121, 121, 121, 121, 121])

In [26]:
arr_10

array([ 21, 121, 121, 121, 121, 121,   7,   7,   7,   7,   7,   7,   7,
         7])

In [27]:
# so we can change value of this array by only first copying array into some other variable.

In [33]:
nre_arr = arr_10.copy()

In [34]:
nre_arr

array([21, 34, 34, 34, 34, 34,  7,  7,  7,  7,  7,  7,  7,  7])

In [38]:
nre_arr[1:6] = 43

In [39]:
nre_arr

array([21, 43, 43, 43, 43, 43,  7,  7,  7,  7,  7,  7,  7,  7])

In [40]:
arr_10

array([21, 34, 34, 34, 34, 34,  7,  7,  7,  7,  7,  7,  7,  7])

In [41]:
# see thats how we can change value of duplicate array by copying original array to it.

# now Lets work with 2D array.

In [44]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# now it is 2d array. so we can get value by indexing

In [47]:
arr_2d[0][0] # [0]--->First row,
             # [0]--->First Column

1

In [48]:
# now to get value of 2nd row 3rd column.
arr_2d[1][2]

6

In [51]:
# get value of 1 column and 2nd row

In [52]:
arr_2d[1][0]

4

In [53]:
# Now to get entire 1st column we can just slice it like list.

In [57]:
# 2nd row
arr_2d[1]

array([4, 5, 6])

In [58]:
# 3rd row
arr_2d[2]

array([7, 8, 9])

In [59]:
# 1st row
arr_2d[0]

array([1, 2, 3])

In [60]:
# now lets just say we want value till 3nd row but from 2nd column

In [62]:
# we can do that by this
arr_2d[:2,1:] # ----> [:2] till 3rd row but --->[1:] from 2nd column

array([[2, 3],
       [5, 6]])

In [63]:
# now lets get value from 1st row to 2nd row but from just first column 

In [65]:
arr_2d[:1,1:]

array([[2, 3]])

In [66]:
# get value till 2nd row

In [69]:
arr_2d[:1] #---> 1 in row mean 1st row

array([[1, 2, 3]])

In [70]:
arr_2d[:2] # value till 2nd row

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
# lets get array with value till 1 to 10

In [72]:
arr_101 = np.arange(1,11)

In [73]:
arr_101

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# array resized to 5 rows and 2 columns.
arr_resized = arr_101.reshape(5,2)

In [77]:
arr_resized

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [78]:
# we can also use this array to do some comparative opertaions

In [79]:
# lets see if values in forst row grater than 5 or not.

In [80]:
arr_resized[1]>5

array([False, False])

In [82]:
arr_resized[:4]>5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True]])

In [83]:
# that show we can do compartaive operations.

In [84]:
# lets get value from array

In [85]:
arr_101[arr_101>5]

array([ 6,  7,  8,  9, 10])

In [86]:
# this will return value from array which is grater than 5

In [87]:
# lets get values less tah 7 from array

In [88]:
arr_101[arr_101<7]

array([1, 2, 3, 4, 5, 6])

In [89]:
# lets create new array and reshape it at instant.

In [94]:
# we craeted array with all 100 values with 5 rows and 20 columns.
arr_1 = np.arange(100).reshape(5,20)

In [95]:
arr_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [97]:
# lets grab values from row 1 to 3 

In [99]:
arr_1[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [100]:
# lets get values from rows 1 to 2 and from column 6 to end

In [101]:
arr_1[0:2,6:]

array([[ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [102]:
# this will give us value from row 1 and 2 and sim from col forward 6

In [103]:
arr_1[2:,10:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
# this will give us value from 2nd row to all and  columns 10 to forward.