In [2]:
import numpy as np
import pandas as pd

# Numpy Arrays.

In [3]:
# we will be working mainly on arrays from numpy library.

In [4]:
# we can create array by using list from pyhton

In [5]:
my_list = [21,3,1998]

In [6]:
# my list is normal python list.

In [7]:
# we can convert it into array by numpy

In [8]:
my_array = np.array(my_list)

In [9]:
my_array

array([  21,    3, 1998])

In [10]:
# now lets see types of these two.

In [12]:
type(my_array)

numpy.ndarray

In [13]:
type(my_list)

list

In [14]:
# see this two have diffrent types

In [15]:
# this is how we can create array.

In [18]:
my_array_two = np.array([1,2,3])

In [19]:
my_array_two

array([1, 2, 3])

In [20]:
# This is another way to create array using numpy.

In [21]:
# now lets see dimenssion of this numpy array we just created.

In [23]:
# ndim(no of dimenssion [] gives no of dimenssion array have.)
# for 1 dimenssion 1 [] will be given
# for 2 dimenssion 2 [] will be given.
my_array.ndim

1

In [24]:
# lets check with my_array_2nd dimenssion

In [25]:
my_array_two.ndim

1

In [26]:
# we can create 2d array like this

In [28]:
my_2d_array = np.array([[1,2,3]])

In [29]:
my_2d_array

array([[1, 2, 3]])

In [30]:
# lets check dimenssion of my_2d_array

In [31]:
my_2d_array.ndim

2

In [32]:
# its 2 dimenssional

In [33]:
# lets create 3 dimenssional arrayy

In [34]:
my_3d_array = np.array([[[1,2,3]]])

In [35]:
my_3d_array.ndim

3

In [36]:
# we can also create matrix.

In [37]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
# this is called matrix with 3 rows and 3 columns. square matrix

In [40]:
# lets create matrix of 2 rows and 3 col. 3d matrix

In [41]:
my_3d_matrix = np.array([[[1,2,3,4],[5,6,7,8]]])

In [42]:
my_3d_matrix.ndim

3

In [43]:
my_3d_matrix

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [44]:
# sim we can do this with list provided to us.

In [45]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list_array = np.array([my_list])

In [46]:
my_list_array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [47]:
# this becam 3d array

In [48]:
my_list_array_2d =  np.array(my_list)

In [49]:
my_list_array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# another way to create array

In [50]:
# this numpy function similar to python range function.

In [52]:
my_range_array = np.arange(1,21)

In [53]:
my_range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
# see this is how it will craete array. by taking 2 numbers 1 to 20.

In [55]:
# lets create another one.

In [56]:
my_top_10 = np.arange(1,11)

In [57]:
my_top_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# this is how we can create array by np.arange

In [59]:
# if we want value from 0 to 100 in array,

In [60]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [61]:
# here you go

In [62]:
# sim like range function in python.
# if we want to skip some of numbers from array we can give skip no, ex.(1,100,2)...so array will look like(1,3,5,7,9....)

In [63]:
# lets see
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [64]:
# see this is how we can create array by skipping some middle values.

# Now we will create array of zero.

In [65]:
np.zeros(3)

array([0., 0., 0.])

In [66]:
# so here we can see by np.zeroes we can give all value in array to be zero

In [67]:
# where 3 is no of columns

In [68]:
# lets create array of zeroes with 5 cols and 5 rows

In [69]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
# Now (5,5) first 5 will be no of rows and other 5 will be no of columns 

In [74]:
# lets create array of uneven size like 3 rows , 2 col

In [75]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [76]:
# sim lets create array of 5 rows and 2 cols

In [77]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# sim we can create array of ones

In [78]:
np.ones(3)

array([1., 1., 1.])

In [79]:
# lets create array of ones with 5 rows and 2 cols

In [88]:
# this is 2d array because of  we are writing brackets inside bracket((5,2))
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
# sim lets create array with 2 rows and 5 cols

In [91]:
# 2d array
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# numpy linspace will return evenly spaced numbers between two values

In [92]:
# so, if we give 1,10 and we want 100 evenly spaced values then use(np.linspace(1,10,100))

In [93]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [94]:
# this is how we can get evenly spaced values.

In [95]:
#lets get 10 evenly spaced values between 1,1000 

In [96]:
np.linspace(1,1000,10)

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [99]:
# linspace for 1,10000

In [100]:
np.linspace(1,100000,10)

array([1.0000e+00, 1.1112e+04, 2.2223e+04, 3.3334e+04, 4.4445e+04,
       5.5556e+04, 6.6667e+04, 7.7778e+04, 8.8889e+04, 1.0000e+05])

# we can also create diagonal matrix

In [101]:
# use np.eye

In [102]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
# np.eye(5) will create diagonal matrix of 5 rows and 5 columns

In [104]:
# lets create diagonal matrix of 3

In [105]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
# sim lets craete 10 diagonal matrix

In [107]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [108]:
# lets create 7 diagonal matrix

In [109]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

# we can create array of random no by(np.random.rand(5))

In [110]:
# lets see

In [111]:
# this will take any 10 random didgits and craete 1d array
np.random.rand(10)


array([0.04195146, 0.08538367, 0.18472778, 0.21907132, 0.8238297 ,
       0.76029486, 0.11774839, 0.76203812, 0.74976825, 0.1521259 ])

In [112]:
# again lets create random values 2D array 

In [113]:
np.random.rand(5,5)

array([[0.97831052, 0.74706189, 0.9833412 , 0.57401848, 0.9565724 ],
       [0.67829136, 0.15735682, 0.1084636 , 0.90870508, 0.56383634],
       [0.68743641, 0.55969097, 0.64982748, 0.46400622, 0.82773546],
       [0.77738351, 0.15648103, 0.69138475, 0.71149894, 0.68556789],
       [0.37124585, 0.69224729, 0.06224633, 0.736702  , 0.71064417]])

In [114]:
# lets create 10 rows and 10 cols random values array

In [115]:
np.random.rand(10,10)

array([[3.87498800e-01, 7.00648248e-01, 1.80793769e-01, 4.02319838e-01,
        1.19958677e-01, 5.99469027e-01, 3.52878090e-01, 8.23018547e-01,
        5.02303169e-01, 9.24632193e-01],
       [1.07239686e-01, 6.53303130e-01, 2.26409680e-01, 6.39742886e-01,
        6.07454566e-01, 4.85133491e-01, 8.54495153e-01, 9.71649755e-01,
        2.43113805e-01, 8.20376938e-01],
       [8.08573522e-01, 1.96760592e-01, 4.29228652e-01, 9.83107055e-01,
        9.10325469e-01, 1.64570788e-02, 8.39328495e-01, 1.69815318e-01,
        5.70778093e-01, 7.73177764e-01],
       [6.74096195e-01, 1.52652254e-04, 1.91114524e-01, 7.87383306e-01,
        1.33542189e-01, 9.28283365e-01, 3.27540198e-01, 5.52001322e-01,
        4.17076688e-01, 4.76935211e-01],
       [8.25031324e-01, 2.81848622e-01, 6.16558029e-01, 2.30856638e-01,
        2.33538975e-03, 1.41991903e-01, 8.12228015e-01, 2.68972179e-01,
        9.09770003e-01, 8.47906445e-01],
       [2.78339834e-01, 5.00044815e-01, 9.15098977e-01, 1.53501879e-03,
   

In [116]:
# also we can get any 10 random integers from between any two numbers

In [118]:
# this will return  only one integer
np.random.randint(100)

72

In [119]:
# to get multiple random no or array of random numbers

In [120]:
np.random.randint(1,100,5)

array([ 9, 52, 31, 57, 95])

In [121]:
# now this will return array of random 5 no from 1,100

In [122]:
# lets try to create 2d array.

In [125]:
# this will choose any random value from 10,100,1000,10000 when given in double (())
np.random.randint((100,1000,10,10000))

array([  87,  297,    4, 3919])

In [127]:
# lets get array of random integers 
np.random.randint(100,1000,10)

array([730, 720, 654, 839, 900, 368, 667, 475, 306, 992])

In [128]:
#  we can arrange array by np.arange(1,24)

In [129]:
np.arange(1,24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [130]:
# lets create array from 0,100 with skip as 10

In [131]:
arr_100 = np.arange(1,100,5)

In [132]:
arr_100

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [133]:
# lets just get 10 random integer

In [134]:
np.random.randint(1,100,20)

array([18, 44, 87, 50, 23, 68, 74, 14, 48, 77,  9, 61, 49, 47, 67, 69, 94,
       73, 73, 20])

# we can use np.reshape to restructure our array

In [137]:
arr_100.reshape(4,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [138]:
# this will creat array with size 4 rows and 5 cols

In [139]:
# lets resize array by using np.arange and np.reshape

In [143]:
arr_34 = np.arange(0,100,10).reshape(2,5)

In [144]:
# this will give us 2 rows and 5 cols

In [145]:
# we can use min,max,sum,mean to get values from array

#### 

In [148]:
# lets get min value from array


In [149]:
arr_34.min()

0

In [150]:
#lets get max value from array

In [151]:
arr_34.max()

90

In [152]:
# lets get mean value from array

In [153]:
arr_34.mean()

45.0

In [154]:
# lets get std value from array

In [155]:
arr_34.std()

28.722813232690143

In [156]:
# to get location of max,min,mean,std values from array we use argmax,argmin,argmean,argstd

In [157]:
arr_34.argmin()

0

In [158]:
arr_34.argmax()

9

In [162]:
# to get shape from array use np.shape

In [163]:
arr_34.shape

(2, 5)

In [164]:
arr_100.shape

(20,)

In [168]:
arr_45 = np.arange(1,100,5)

In [169]:
arr_45


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [173]:
re_arr = arr_45.reshape(4,5)

In [174]:
re_arr

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [175]:
re_arr.shape

(4, 5)

# to get dataype from array use np.dtypes

In [179]:
arr_100.dtype

dtype('int32')

In [180]:
arr_34.dtype

dtype('int32')