In [1]:
import numpy as np

# Numpy Operations.

In [2]:
# we will perform various operations here.

In [3]:
arr = np.arange(11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# we can add array to each other as well

In [6]:
arr_2 = arr+arr

In [7]:
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
# lets see for multiplication.

In [9]:
arr_2**2

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [10]:
# This will give us square of each array value.

In [11]:
# lets see for division.

In [12]:
arr_2//2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [14]:
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
sqaure_arr = arr_2**2

In [16]:
sqaure_arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [17]:
# also add two array with each other.

In [18]:
add_array = sqaure_arr+arr_2

In [19]:
add_array

array([  0,   6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

In [20]:
# we can also add certain value to all values in array.

In [21]:
sqaure_arr_3 = sqaure_arr+3

In [22]:
sqaure_arr_3

array([  3,   7,  19,  39,  67, 103, 147, 199, 259, 327, 403])

In [23]:
# sim we can substract value from all array values.

In [24]:
# lets see for division.

In [25]:
arr_div = arr/arr

C:\Users\91916\AppData\Local\Temp\ipykernel_30192\3559639798.py:1: RuntimeWarning: invalid value encountered in divide
  arr_div = arr/arr


In [26]:
arr_div

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
# nan will be given when 0 will be dividing to 0.

In [28]:
# similarly if we divide anything by zero it will give us infinity

In [29]:
1/arr

C:\Users\91916\AppData\Local\Temp\ipykernel_30192\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [30]:
# we can also get square root values from array.

In [31]:
arr_sqrt = np.sqrt(sqaure_arr_3)

In [32]:
arr_sqrt

array([ 1.73205081,  2.64575131,  4.35889894,  6.244998  ,  8.18535277,
       10.14889157, 12.12435565, 14.10673598, 16.09347694, 18.08314132,
       20.0748599 ])

In [33]:
# we will get sqrt by np.sqrt

In [34]:
# we can also get exponential value by np.exp

In [35]:
exp_array = np.exp(sqaure_arr_3)

In [36]:
exp_array

array([2.00855369e+001, 1.09663316e+003, 1.78482301e+008, 8.65934004e+016,
       1.25236317e+029, 5.39922761e+044, 6.93887142e+063, 2.65828719e+086,
       3.03578362e+112, 1.03346455e+142, 1.04876022e+175])